Repository nortikin/sverchok, pull requests merged in 2020-09, with the labels that each got.

#3507 Sockets refactoring
  core/socket_conversions.py
  core/sockets.py
  core/update_system.py
  node_tree.py
  nodes/analyzer/mesh_select.py
  nodes/curve/arc_3pt.py
  nodes/curve/arc_sed.py
  nodes/curve/bezier_spline.py
  nodes/curve/cast_curve.py
  nodes/curve/catenary_curve.py
  nodes/curve/circlify.py
  nodes/curve/intersect_curve_plane.py
  nodes/curve/line.py
  nodes/curve/nearest_point.py
  nodes/curve/offset_mk2.py
  nodes/curve/ortho_project.py
  nodes/field/attractor_field_mk2.py
  nodes/field/scalar_field_eval.py
  nodes/field/scalar_field_point.py
  nodes/field/vector_field_apply.py
  nodes/field/vector_field_eval.py
  nodes/generator/basic_3pt_arc.py
  nodes/generator/script1_lite.py
  nodes/generators_extended/conic_section.py
  nodes/list_mutators/vd_attr_node.py
  nodes/modifier_make/pipe_tubes.py
  nodes/modifier_make/voronoi_sphere.py
  nodes/number/easing.py
  nodes/surface/extrude_curve.py
  nodes/surface/extrude_point.py
  nodes/surface/extrude_vector.py
  nodes/surface/implicit_surface_raycast.py
  nodes/surface/nearest_point.py
  nodes/surface/ortho_project.py
  nodes/surface/plane.py
  nodes/surface/raycast.py
  nodes/surface/revolution_surface.py
  nodes/surface/sphere.py
  nodes/surface/taper_sweep.py
  nodes/transforms/transform_mesh.py
  nodes/vector/attractor.py
  nodes/vector/interpolation_stripes.py
  nodes/vector/vertices_sort.py
  nodes/viz/vd_draw_experimental.py
  nodes/viz/viewer_gp.py
  old_nodes/attractor_field.py
  old_nodes/offset.py
  tests/references/box.json
  tests/references/cylinder.json
  tests/references/script_uv.json
  tests/references/torus.json
  tests/references/viewer_text.blend.json
  utils/sv_IO_panel_tools.py
Labels: Performance

#3530 "Hollow solid" node
  docs/nodes/solid/hollow_solid.rst
  docs/nodes/solid/solid_index.rst
  index.md
  nodes/solid/hollow_solid.py
  ui/icons/sv_hollow_solid.png
  ui/icons/svg/sv_hollow_solid.svg
Labels: Solids

#3537 FreeCAD: start supporting "native" curves where possible
  nodes/solid/wire_face.py
  utils/curve/freecad.py
  utils/curve/primitives.py
  utils/surface/freecad.py
Labels: NURBS, Solids

#3496 add string to vector conversion
  core/socket_conversions.py
Labels: Proposal

#3550 Do not update whole tree upon `show` attribute switching of a node tree
  node_tree.py
  nodes/viz/vd_draw_experimental.py
  nodes/viz/viewer_idx28.py
Labels: Performance

#3558 NURBS Sweep node
  docs/nodes/surface/nurbs_sweep.rst
  docs/nodes/surface/surface_index.rst
  index.md
  nodes/curve/iso_uv_curve.py
  nodes/surface/nurbs_sweep.py
  utils/curve/algorithms.py
  utils/curve/nurbs.py
  utils/math.py
  utils/surface/freecad.py
  utils/surface/nurbs.py
Labels: NURBS

#3580 Solid Boolean node: upgrade
  docs/nodes/solid/solid_boolean.rst
  nodes/solid/solid_boolean.py
  utils/solid.py
Labels: Solids

#3588 "General Fuse" node for Solids
  docs/nodes/solid/general_fuse.rst
  docs/nodes/solid/solid_boolean.rst
  docs/nodes/solid/solid_index.rst
  index.md
  json_examples/Shapes/Technical_ring_with_holes.json
  nodes/solid/fillet_solid.py
  nodes/solid/general_fuse.py
  nodes/solid/solid_boolean.py
  tests/general_fuse_tests.py
  tests/tree_import_tests.py
  ui/icons/sv_general_fuse.png
  ui/icons/svg/sv_general_fuse.svg
  utils/solid.py
Labels: Solids

#3593 Solid Analyzer nodes
  data_structure.py
  docs/nodes/solid/area.rst
  docs/nodes/solid/center_of_mass.rst
  docs/nodes/solid/face_area.rst
  docs/nodes/solid/fillet_solid.rst
  docs/nodes/solid/is_closed.rst
  docs/nodes/solid/polygon_face.rst
  docs/nodes/solid/refine.rst
  docs/nodes/solid/solid_index.rst
  docs/nodes/solid/validate.rst
  docs/nodes/solid/volume.rst
  index.md
  menu.py
  nodes/solid/area.py
  nodes/solid/center_of_mass.py
  nodes/solid/face_area.py
  nodes/solid/is_closed.py
  nodes/solid/refine.py
  nodes/solid/validate.py
  nodes/solid/volume.py
  tests/data_structure_tests.py
  tests/ui_tests.py
  ui/nodeview_space_menu.py
  ui/sv_icons.py
Labels: Solids
